### ISSUE TITLE
Suggestion: Mob Radar Stage

### ISSUE THREAD

**Issue by jonqrandom** [Darkhax-Minecraft/JourneyMapStages#1]
is it possible/simple enough to allow access to the minimap but disable the mob radar, and make the mob radar a separate stage?

**Comment by Darkhax** [comment]
I have been working with the JourneyMap devs for a version of the API that would allow this. Currently they are not able to release this API so I am using a less powerful API that does not easily allow this. If their new API ever comes out I will add this feature.

**Comment by jonqrandom** [comment]
awesome, thank you! and thanks for all the great mods, too :)

**Comment by Fireztonez** [comment]
Any news about that feature? I think that should be realy great for my modpack to!

**Comment by Darkhax** [comment]
Not until JourneyMap puts out their update.
