### ISSUE TITLE
/home

### ISSUE THREAD

**Issue by reso59** [Darkhax-Minecraft/JourneyMapStages#2]
using /home with this mod installed disables your minimap and deletes your waypoints as if you haven't unlocked them yet.

**Comment by Darkhax** [comment]
I've pushed a new version which should fix this issue. I would appreciate it if you could test for me. These should only need to be installed on the client. 

https://minecraft.curseforge.com/projects/bookshelf/files/2540877
https://minecraft.curseforge.com/projects/game-stages/files/2540972
https://minecraft.curseforge.com/projects/journeymapstages/files/2540980

The jmap stages file may need a few minutes to be approved.

**Comment by Darkhax** [comment]
Going to assume this was fixed, and if it wasn't 2.0 would have.
