### ISSUE TITLE
Default Setting Issue

### ISSUE THREAD

**Issue by ggtechyguy** [Darkhax-Minecraft/JourneyMapStages#3]
It appears, that without anything scripted, Fullscreen Map view is defaulted behind a nothing stage and cannot be unlocked or opened.  Not an issue once scripted, but figured it was an unintended default.

**Comment by Darkhax** [comment]
Thanks for the report, sorry it took me so long to respond. An update has been pushed which should fix this issue and a similar one for the waypoint editor gui. This new version will automatically appear on Curse in a few minutes.
