### ISSUE TITLE
Suggestions: Coordinates stages and Cave map stages

### ISSUE THREAD

**Issue by Fireztonez** [Darkhax-Minecraft/JourneyMapStages#4]
For my modpack, I wan't to have Journey map, but stages in multiple step, for unlock somes new functions... Like that, you start with a basic mini-map, without possibility to see the complete. After you unlock the big map, giving you the possibility to realy see the world around you! And after you unlock the possibility to add waypoints... But 2 things is missing for what I realy want I think;

- Possibility to stage the X-Y-Z coordinates, that way the player need to realy be carefull where is go, ans not just remember the coordinates of each things!

- Possibility to disable the underground mapping. Like that you can't see over the wall if have a cave or something, can't see if have lava lac or no... The  underground mapping will need to be unlock. 

That features will change I think completely the way to play with Journey Map, if no specials features is available from the beginning!!

I really hope you can look to make something for that, if not, I probably need to look for other map before unlock journey map :/

Fireztonez

**Comment by Darkhax** [comment]
Unfortunately I do not have access to a public API for Journey Map, so I have to be very hacky when adding new features. I had worked with their team to get a new API, however do to IRL issues JMap has been in update limbo. I am currently waiting on that before I do much more with this.
