### ISSUE TITLE
Map turns on when going between dimensions

### ISSUE THREAD

**Issue by F9Alejandro** [Darkhax-Minecraft/JourneyMapStages#5]
After turning off Journey map and going to a different dimension it will be toggled back on (like the config file is being reset). Is there a possibility to have it so when you change dimension or load in to the world if you have journey map unlocked (that seems to be what is possibly causing it to occur).

Thanks in advanced.

**Comment by Darkhax** [comment]
Is this with the 2.0.0 version of the mod?
